name: Publish to NuGet
on:
  push:
    tags:
      - 'v*' # only publish on tag with semantic versioning

jobs:
  build-and-publish-TabtTabGo-Storage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish to NuGet
        uses: tabtabgo/publish-to-nuget-action@v1.3
        with:
          project_path: 'src/TabTabGo.Storage/TabTabGo.Storage.csproj'
          package_version: ${GITHUB_REF#refs/*/v}
          package_name: 'TabTabGo.Storage'
          nuget_api_key: ${{ secrets.NUGET_API_KEY }}
  
  build-and-publish-TabtTabGo-Storage-Services:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish to NuGet
        uses: tabtabgo/publish-to-nuget-action@v1.3
        with:
          project_path: 'src/TabTabGo.Storage.Services/TabTabGo.Storage.Services.csproj'
          package_version: ${GITHUB_REF#refs/*/v}
          package_name: 'TabTabGo.Storage.Services'
          nuget_api_key: ${{ secrets.NUGET_API_KEY }}
  
  build-and-publish-TabtTabGo-Storage-Data-EF:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish to NuGet
        uses: tabtabgo/publish-to-nuget-action@v1.3
        with:
          project_path: 'src/TabTabGo.Storage.Data.EF/TabTabGo.Storage.Data.EF.csproj'
          package_version: ${GITHUB_REF#refs/*/v}
          package_name: 'TabTabGo.Storage.Data.EF'
          nuget_api_key: ${{ secrets.NUGET_API_KEY }}
          
  build-and-publish-TabtTabGo-Storage-Aws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish to NuGet
        uses: tabtabgo/publish-to-nuget-action@v1.3
        with:
          project_path: 'src/TabTabGo.Storage.Aws/TabTabGo.Storage.Aws.csproj'
          package_version: ${GITHUB_REF#refs/*/v}
          package_name: 'TabTabGo.Storage.Aws'
          nuget_api_key: ${{ secrets.NUGET_API_KEY }}
  
  build-and-publish-TabtTabGo-Storage-Azure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish to NuGet
        uses: tabtabgo/publish-to-nuget-action@v1.3
        with:
          project_path: 'src/TabTabGo.Storage.AzureStorage/TabTabGo.Storage.AzureStorage.csproj'
          package_version: ${GITHUB_REF#refs/*/v}
          package_name: 'TabTabGo.Storage.AzureStorage'
          nuget_api_key: ${{ secrets.NUGET_API_KEY }}
  
  build-and-publish-TabtTabGo-Storage-Data-FileStorage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish to NuGet
        uses: tabtabgo/publish-to-nuget-action@v1.3
        with:
          project_path: 'src/TabTabGo.Storage.FileStorage/TabTabGo.Storage.FileStorage.csproj'
          package_version: ${GITHUB_REF#refs/*/v}
          package_name: 'TabTabGo.Storage.FileStorage'
          nuget_api_key: ${{ secrets.NUGET_API_KEY }}