name: Publish to NuGet
on:
  push:
    tags:
      - 'v*' # only publish on tag with semantic versioning

jobs:
  build-and-publish-TabtTabGo-Storage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish TabTabGo.Storage to NuGet
        uses: tabtabgo/publish-to-nuget-action@v1.7
        with:
          project_path: 'src/TabTabGo.Storage/TabTabGo.Storage.csproj'
          package_version: ${GITHUB_REF#refs/*/v}
          package_name: 'TabTabGo.Storage'
          nuget_api_key: ${{ secrets.NUGET_API_KEY }}
  
      - name: Publish TabTabGo.Storage.Services to NuGet
        uses: tabtabgo/publish-to-nuget-action@v1.7
        with:
          project_path: 'src/TabTabGo.Storage.Services/TabTabGo.Storage.Services.csproj'
          package_version: ${GITHUB_REF#refs/*/v}
          package_name: 'TabTabGo.Storage.Services'
          nuget_api_key: ${{ secrets.NUGET_API_KEY }}
  
      - name: Publish TabTabGo.Storage.Data.EF to NuGet
        uses: tabtabgo/publish-to-nuget-action@v1.7
        with:
          project_path: 'src/TabTabGo.Storage.Data.EF/TabTabGo.Storage.Data.EF.csproj'
          package_version: ${GITHUB_REF#refs/*/v}
          package_name: 'TabTabGo.Storage.Data.EF'
          nuget_api_key: ${{ secrets.NUGET_API_KEY }}
          
      - name: Publish TabTabGo.Storage.Aws to NuGet
        uses: tabtabgo/publish-to-nuget-action@v1.7
        with:
          project_path: 'src/TabTabGo.Storage.Aws/TabTabGo.Storage.Aws.csproj'
          package_version: ${GITHUB_REF#refs/*/v}
          package_name: 'TabTabGo.Storage.Aws'
          nuget_api_key: ${{ secrets.NUGET_API_KEY }}
  
      - name: Publish TabTabGo.Storage.AzureStorage to NuGet
        uses: tabtabgo/publish-to-nuget-action@v1.7
        with:
          project_path: 'src/TabTabGo.Storage.AzureStorage/TabTabGo.Storage.Azure.csproj'
          package_version: ${GITHUB_REF#refs/*/v}
          package_name: 'TabTabGo.Storage.Azure'
          nuget_api_key: ${{ secrets.NUGET_API_KEY }}
  
      - name: Publish TabTabGo.Storage.FileStorage to NuGet
        uses: tabtabgo/publish-to-nuget-action@v1.7
        with:
          project_path: 'src/TabTabGo.Storage.FileStorage/TabTabGo.Storage.FileStorage.csproj'
          package_version: ${GITHUB_REF#refs/*/v}
          package_name: 'TabTabGo.Storage.FileStorage'
          nuget_api_key: ${{ secrets.NUGET_API_KEY }}